### ISSUE TITLE
MissingMethodException: Method Starcounter.Session.get_ActiveWebSocket() not found

### ISSUE THREAD

**Issue by PatrykSzwer** [joozek78/starcounter-async#1]
During work with Kitchensink app We noticed that pages that use `AsyncInputHandlers` methods stopped working.

Reproduction:
1. Run [Kitchensink app](https://github.com/Starcounter/KitchenSink) branch `master-2.4`
2. Go to http://localhost:8080/KitchenSink/ProgressBar
3. Click on the `download (imaginary) file!`.

Exception that occurs after that:
```
System.Exception: ScErrUnhandledException (SCERR1069): An unhandled exception was detected.
Version: 2.4.0.6025.
Help page: https://docs.starcounter.io/?q=SCERR1069.
   at StarcounterInternal.Hosting.Processor.<>c__DisplayClass3_0.<RunTaskNoScheduling>b__0() in C:\TeamCity\BuildAgent\work\sc-17818\Level1\src\Starcounter.Hosting\StarcounterInternal.Hosting\Processor.cs:line 139
   at Starcounter.Internal.StarcounterEnvironment.RunWithinApplicationInternal(String desiredAppName, Action action) in C:\TeamCity\BuildAgent\work\sc-17818\Level1\src\Starcounter.Internal\Mock\StarcounterEnvironment.cs:line 146
   at StarcounterInternal.Hosting.Processor.RunTaskNoScheduling(Action userAction, String appName) in C:\TeamCity\BuildAgent\work\sc-17818\Level1\src\Starcounter.Hosting\StarcounterInternal.Hosting\Processor.cs:line 122
   at Starcounter.DbSession.GetAndExecuteQueuedTasks(Action`2 taskExecutionMethod) in C:\TeamCity\BuildAgent\work\sc-17818\Level1\src\Starcounter\DbSession.cs:line 181
   at StarcounterInternal.Hosting.Processor.RunTask(IntPtr hTask) in C:\TeamCity\BuildAgent\work\sc-17818\Level1\src\Starcounter.Hosting\StarcounterInternal.Hosting\Processor.cs:line 169
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\TeamCity\BuildAgent\work\sc-17818\Level1\src\Starcounter.Hosting\StarcounterInternal.Hosting\Processor.cs:line 82
HResult=-2146233088
HelpLink=https://docs.starcounter.io/?q=SCERR1069
---> System.MissingMethodException: Method not found: 'Starcounter.WebSocket Starcounter.Session.get_ActiveWebSocket()'.
   at Joozek78.Star.Async.Internal.StarcounterSessionSynchronizationContext.<Post>b__5_0(Session session, String sessionId)
   at Starcounter.Session.Use(Action action)
   at Starcounter.DbSession.<>c__DisplayClass5_0.<RunAsync>b__0() in C:\TeamCity\BuildAgent\work\sc-17818\Level1\src\Starcounter\DbSession.cs:line 217
   at Starcounter.Task.Run() in C:\TeamCity\BuildAgent\work\sc-17818\Level1\src\Starcounter\DbSession.cs:line 101
HResult=-2146233069
```

**Comment by joozek78** [comment]
It's because property `Session.ActiveWebSocket` is no longer a `WebSocket`, but rather a simple `object`. @chrhol can you say why is that? How should [this line](https://github.com/joozek78/starcounter-async/blob/master/StarcounterAsyncHandlers/Internal/StarcounterSessionSynchronizationContext.cs#L60) now look like?

**Comment by chrhol** [comment]
Sorry for the delay. Sitting in a workshop the whole day. 

This was an unfortunate way to decouple xson from Starcounter specific types. I found no good way to abstract/decouple websocket from Session so I made it an object instead. 

You have to cast it to the correct type, so the line should look like this:
`((WebSocket)session.ActiveWebSocket).Disconnect(...`

**Comment by joozek78** [comment]
You can update to version [2.0.0](https://www.nuget.org/packages/Joozek78.Starcounter.Async/2.0.0) of Joozek78.Starcounter.Async now

**Comment by PatrykSzwer** [comment]
PR with new version is created in kitchensink repository (https://github.com/Starcounter/KitchenSink/pull/306), but I can tell already that this issue is fixed. Great job!
